// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://parabank.parasoft.com/parabank/index.htm;jsessionid=DE331C85194320B864F83CE5C13893A1");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.id("customer.firstName")).click();
    driver.findElement(By.id("customer.firstName")).sendKeys("uu");
    driver.findElement(By.id("customer.lastName")).click();
    driver.findElement(By.id("customer.lastName")).sendKeys("vv");
    driver.findElement(By.id("customer.address.street")).click();
    driver.findElement(By.id("customer.address.street")).sendKeys("rajkot");
    driver.findElement(By.id("customer.address.city")).click();
    driver.findElement(By.id("customer.address.city")).sendKeys("rajkot");
    driver.findElement(By.id("customer.address.state")).click();
    driver.findElement(By.id("customer.address.state")).sendKeys("gujrat");
    driver.findElement(By.id("customer.address.zipCode")).click();
    driver.findElement(By.id("customer.address.zipCode")).sendKeys("258");
    driver.findElement(By.id("customer.phoneNumber")).click();
    driver.findElement(By.id("customer.phoneNumber")).sendKeys("5252635263");
    driver.findElement(By.id("customer.ssn")).click();
    driver.findElement(By.id("customer.ssn")).sendKeys("5658");
    driver.findElement(By.id("customer.username")).click();
    driver.findElement(By.id("customer.username")).sendKeys("uu");
    driver.findElement(By.id("customer.password")).click();
    driver.findElement(By.id("customer.password")).sendKeys("345");
    driver.findElement(By.id("repeatedPassword")).click();
    driver.findElement(By.id("repeatedPassword")).sendKeys("345");
    driver.findElement(By.cssSelector("td > .button")).click();
  }
}
